### ISSUE TITLE
Large files handling 

### ISSUE THREAD

**Issue by darichailu** [hidekuma/flask-s3-viewer#1]
does this work for large files upload and download?

**Comment by hidekuma** [comment]
Thank you for your attention.
Resolved now. (0.0.12)
If you want to controll large files (maybe larger than 5MB), check this [link](https://github.com/hidekuma/flask-s3up#controll-large-files).

**Comment by darichailu** [comment]
Great, that is amazing. I'll play with it and let me know. It would help if you have a setup instruction

**Comment by hidekuma** [comment]
@darichailu , I'm late. sorry about that.
flask-s3up's docs can be found [here](https://flask-s3up.readthedocs.io/en/latest/usage/configuration/#controll-large-files).

**Comment by darichailu** [comment]
Thanks for your response. I'll you know what I've found.

**Comment by darichailu** [comment]
how do you handle security when accessing bucket(s)? The documentation suggests using security key and secure access key. I don't think that is secure. do you plan using cognito or session token?

**Comment by hidekuma** [comment]
Unfortunately when i was making FlaskS3up, i have didn't think about using AWS cognito. 
but you can block users who accessing bucket(s) on WEB APPLICATION.
I recommnad using `before_request` function.
```python
# Apply FlaskS3Up blueprint
s3up.register()

@app.route('/index')
def index():
    return 'Your app index page'

@app.before_request
def before_request():
    # add your login logic or something
    print('before request!')
```
Please answer any other questions or suggestions. and can you explain about `session token`?

++As for cognito, I'll think about whether i can handle it in future improvements.

**Comment by darichailu** [comment]
Thanks. I was thinking about sts with temp security credentials
