### ISSUE TITLE
Wrong filenames when using python 3.12 , NoSuchKey when calling the ListObjectsV2 when using endpoint_url

### ISSUE THREAD

**Issue by dmitrydvornichenko** [hidekuma/flask-s3-viewer#13]
Thank you for your utility. We use it for the whole team and pretty satisfied with the functionality.

I deployed it in docker container 3 years ago. Now I need to change the server, so I tried to rebuild with new python.
Here is the Dockerfile

```
FROM python:3.7
RUN pip install --no-cache-dir flask flask_s3_viewer
COPY app.py /
ENTRYPOINT ["python", "app.py"]
```
Here is my app.py

```
import sys
import os
from flask import Flask
from flask_s3_viewer import FlaskS3Viewer
#from flask_s3_viewer.aws.ref import Region

app = Flask(__name__)

app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 1
app.config['TEMPLATES_AUTO_RELOAD'] = True

ACCESS_KEY = os.environ['AWS_ACCESS_KEY_ID']
SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
#S3_ENDPOINT = os.environ['S3_ENDPOINT']
S3_BUCKET_NAME = os.environ['S3_BUCKET_NAME']

s3viewer = FlaskS3Viewer(
    app, # Flask app
    namespace='s3', # namespace be unique
    template_namespace='mdl', # set template
    object_hostname='https://static.example.com', # file's hostname
    allowed_extensions={}, # allowed extension
    config={ # Bucket configs and else
        'profile_name': 'default',
        'access_key': ACCESS_KEY,
            'secret_key': SECRET_ACCESS_KEY,
            'region_name': 'us-east-1',
            #'endpoint_url': S3_ENDPOINT,
            'bucket_name': S3_BUCKET_NAME,
            'cache_dir': '/tmp/flask_s3_viewer',
            'use_cache': True,
            'ttl': 86400,
        }
    )

s3viewer.register()

@app.route('/index')
def index():
    return 'Your app index page'

if __name__ == '__main__':
    debug = False  # Default value
    if len(sys.argv) > 1 and sys.argv[1] == 'test':
        debug = True
    app.run(debug=debug, host="0.0.0.0", port=8080)
```

I got two problems:
1. When using endpoint_url, botocore gives me
`botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.`
When commenting endpoint_url as you can see in app.py, everything goes fine
2. When using python:3.12-alpine instead of python:3.7 , when I try to download "test.png" from UI, it gives me file with a name "b'test.png'". After rollback to python 3.7 the problem disappeared.

Now it works fine but maybe these notes will be useful for ya.
Best regards.

**Comment by hidekuma** [comment]
@dmitrydvornichenko 

A bit untested, but I've fixed it. 0.3.0
Due to lack of testing, the stable version is still 0.2.6.

Regarding the endpoint_url, please note that it was created for use in s3 compaitible like ceph.
