### ISSUE TITLE
Issues/features

### ISSUE THREAD

**Issue by joaomnmoreira** [hidekuma/flask-s3-viewer#6]
Hi!

Congrats! Nice work!

This is a mix between issues and new features.

Is it possible:
1. To trunk to a folder bucket? (ex: 'bucket_name': 'bucket/folder');
2. To have the possibility of ordering, by name, created date and size?
3. To search either in the file path and also in all bucket?

Thanks in advance!

Best regards,
João Moreira

**Comment by hidekuma** [comment]
Sorry I'm late.
2,3 is not supproted yet.

and 1 is possible now.
- https://hidekuma.github.io/flask-s3-viewer/html/usage/configuration.html#mount-a-specific-path-in-a-bucket-for-browsing

Thank you for your interest.
